apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  rules:
  - host: argocd.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: https
