apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: golang
  name: golang
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: golang
status:
  loadBalancer: {}
