apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: golang
  name: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: golang
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: golang
    spec:
      containers:
      - args:
        - gin
        - -a
        - "8080"
        - --all
        - -i
        - run
        - server.go
        env:
        - name: REDIS_HOST
          value: redis
        - name: VIMWIKI
          value: /vimwiki
        image: golang
        imagePullPolicy: ""
        name: golang
        ports:
        - containerPort: 8080
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /src/
          name: golang-claim0
        - mountPath: /vimwiki
          name: golang-claim1
        workingDir: /src
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: golang-claim0
        persistentVolumeClaim:
          claimName: golang-claim0
      - name: golang-claim1
        persistentVolumeClaim:
          claimName: golang-claim1
status: {}
