apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  rules:
  - host: grafana.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: http
